name: py36-keras-simpleRNN
channels:
- conda-forge
- defaults
dependencies:
- backports=1.0=py36_0
- backports.weakref=1.0rc1=py36_0
- bleach=1.5.0=py36_0
- certifi=2016.2.28=py36_0
- cycler=0.10.0=py36_0
- glib=2.50.2=1
- h5py=2.7.0=np113py36_0
- hdf5=1.8.17=2
- ipython=6.1.0=py36_0
- ipython_genutils=0.2.0=py36_0
- keras=2.0.5=py36_0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libgpuarray=0.6.9=0
- libiconv=1.14=0
- libprotobuf=3.4.0=0
- libxcb=1.12=1
- libxml2=2.9.4=0
- mkl=2017.0.3=0
- mkl-service=1.1.2=py36_3
- numpy=1.13.1=py36_0
- openssl=1.0.2l=0
- path.py=10.3.1=py36_0
- pip=9.0.1=py36_1
- pygpu=0.6.9=py36_0
- python=3.6.2=0
- pyyaml=3.12=py36_0
- scipy=0.19.1=np113py36_0
- setuptools=36.4.0=py36_1
- six=1.10.0=py36_0
- tensorflow=1.3.0=0
- tensorflow-base=1.3.0=py36h5293eaa_1
- tensorflow-tensorboard=0.1.5=py36_0
- theano=0.9.0=py36_0
- wheel=0.29.0=py36_0
- yaml=0.1.6=0
- pip:
  - ipython-genutils==0.2.0
  - prompt-toolkit==1.0.15

